apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-cloud-on-kubernetes
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: platform
  source:
    path: platform/elastic-cloud-on-kubernetes
    repoURL: https://github.com/dbackeus/activedeployment.git
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
    syncOptions:
      - ServerSideApply=true
  ignoreDifferences:
    - kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
