apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: platform
  source:
    path: platform/kube-prometheus-stack
    repoURL: https://github.com/dbackeus/activedeployment.git
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
    syncOptions:
      - ServerSideApply=true
