apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
spec:
  project: default
  source:
    chart: reloader
    repoURL: https://stakater.github.io/stakater-charts
    targetRevision: 1.0.16
  destination:
    server: "https://kubernetes.default.svc"
    namespace: reloader
  syncPolicy:
    syncOptions:
    - CreateNamespace=true