apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-cloud-on-kubernetes
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    server: https://kubernetes.default.svc
  project: platform
  source:
    path: platform/elastic-cloud-on-kubernetes
    repoURL: https://github.com/reclaim-the-stack/get-started.git
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
    syncOptions:
      - ServerSideApply=true