apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # NOTE: The postgres-operator-examples does not do any proper version
  # management via git tags so we have just locked it to the last commit SHA.
  - github.com/CrunchyData/postgres-operator-examples/kustomize/install/namespace?ref=f1766db0b50ad2ae8ff35a599a16e11eefbd9f9c
  - github.com/CrunchyData/postgres-operator-examples/kustomize/install/default?ref=f1766db0b50ad2ae8ff35a599a16e11eefbd9f9c
  - ./podmonitor.yaml

# Fix for ArgoCD unable to apply big objects without Replace
patches:
  - target:
      kind: CustomResourceDefinition
      name: ".*"
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: Replace=true
