apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # NOTE: The postgres-operator-examples does not do any proper version
  # management via git tags so we have just locked it to the latest commit SHA.
  - github.com/CrunchyData/postgres-operator-examples/kustomize/install/namespace?ref=9a3b808f309b2eb24da961dbadc189750e88ec48
  - github.com/CrunchyData/postgres-operator-examples/kustomize/install/default?ref=9a3b808f309b2eb24da961dbadc189750e88ec48
  - ./podmonitor.yaml

# Dashboards origin: https://github.com/CrunchyData/postgres-operator-examples/tree/f14aeff743f8c48482ac22f9467b53945a0d568d/kustomize/monitoring/dashboards
configMapGenerator:
  - name: crunchy-postgres-dashboards
    namespace: monitoring
    options:
      annotations:
        argocd.argoproj.io/sync-options: Replace=true
      labels:
        grafana_dashboard: "1"
    files:
      - dashboards/pgbackrest.json
      - dashboards/postgresql.json
      - dashboards/queries.json
generatorOptions:
  disableNameSuffixHash: true