apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: crunchy-postgres-exporter
  namespace: postgres-operator
spec:
  selector:
    matchLabels:
      postgres-operator.crunchydata.com/crunchy-postgres-exporter: "true"
  namespaceSelector:
    matchNames:
      - default
  podMetricsEndpoints:
    - port: exporter
      # Simplified relabelings based on https://github.com/CrunchyData/postgres-operator-examples/blob/main/kustomize/monitoring/prometheus-config.yaml.
      relabelings:
        # pgo metrics stack sometimes rely on `kubernetes_namespace` instead of `namespace` in dashboard and rules
        - action: replace
          sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: kubernetes_namespace
        # Add `pod` label based on pod name
        - action: replace
          sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        # Add `pg_cluster` label from `postgres-operator.crunchydata.com/cluster: <postgres-cluster-name>`
        - action: replace
          sourceLabels:
            [
              __meta_kubernetes_pod_label_postgres_operator_crunchydata_com_cluster,
            ]
          targetLabel: pg_cluster
        - action: replace
          sourceLabels: [__meta_kubernetes_pod_ip]
          targetLabel: ip
        # Adds `deployment` label from `postgres-operator.crunchydata.com/instance: <postgres-cluster-name>-<instance>`
        - action: replace
          sourceLabels:
            [
              __meta_kubernetes_pod_label_postgres_operator_crunchydata_com_instance,
            ]
          targetLabel: deployment
        # Adds `role` label from `postgres-operator.crunchydata.com/role: <master|slave>`
        - action: replace
          sourceLabels:
            [__meta_kubernetes_pod_label_postgres_operator_crunchydata_com_role]
          targetLabel: role
